//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModuleManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cat1 {
            get {
                object obj = ResourceManager.GetObject("cat-1", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] cat2
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] cat3
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] cat4
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] cat5
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] cat6
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] cat7
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] cat8
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] cat9
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] cat10
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] cat11
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] cat12
        {
            get
            {
                object obj = ResourceManager.GetObject("cat-12", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] rainbow
        {
            get
            {
                object obj = ResourceManager.GetObject("rainbow2", resourceCulture);
                return ((byte[])(obj));
            }
        }

    }
}
